### ISSUE TITLE
Cannot login with Wunderlist

### ISSUE THREAD

**Issue by konigkarl** [nikriek/restock#2]
I have installed Restock app but I cannot authorize an app in Wunderlist, after i give permissions site restock.thinkcarl.com gives no response. Your app seems to be fairly useful so please repair this problem.

PS tested via WiFi & GSM, test phones: Lenovo Vibe Shot, LG K10 and Videocon A10 and multiple browsers

**Comment by nikriek** [comment]
Cool that you found our project! We developed the project during a hackathon. As far as I remember we had problems with directly signing in to Wunderlist from a mobile device. We proxied the login through a custom backend on restock.thinkcarl.com. @MasterCarl took it offline I guess...

**Comment by nikriek** [comment]
Server can be found here: https://github.com/nikriek/restock/blob/master/Wunderlist-redirect/server.js
